sudo: required

services:
  - docker

language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      env: CONDA_PY=2.7
    - os: linux
      dist: trusty
      env: CONDA_PY=3.5
    - os: osx
      env: CONDA_PY=2.7
    - os: osx
      env: CONDA_PY=3.5

install:
  # Set the anaconda environment
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export EPICS_HOST_ARCH=darwin-x86;
      if [[ "$CONDA_PY" == "2.7" ]]; then
        curl https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -o miniconda.sh;
      else
        curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh;
      fi
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      hash -r;
      conda config --set always_yes yes --set changeps1 no;
      conda update -q --all;
      conda config --add channels defaults;
      conda config --add channels xiaoqiangwang;
      conda install conda-build numpy swig pip anaconda-client;
    else
      docker pull continuumio/anaconda-build-linux-64:latest;
      mkdir -m 0777 -p $HOME/miniconda/conda-bld/${TRAVIS_OS_NAME}-64;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      conda build conda-recipe;
    else
       ./conda_build_in_docker.sh `pwd` $HOME/miniconda/conda-bld/${TRAVIS_OS_NAME}-64 xiaoqiangwang;
    fi

after_success:
    - which pip
    - if [[ ! -z "$TRAVIS_TAG" ]]; then
        anaconda -t $CONDA_TOKEN upload --force $HOME/miniconda/conda-bld/${TRAVIS_OS_NAME}-64/*.tar.bz2;
        echo [distutils]                > ~/.pypirc;
        echo index-servers = mypypi    >> ~/.pypirc;
        echo [mypypi]                  >> ~/.pypirc;
        echo repository=$PYPI_URL      >> ~/.pypirc;
        echo username=$PYPI_USER       >> ~/.pypirc;
        echo password=$PYPI_PASSWORD   >> ~/.pypirc;
        export EPICS_BASE=$HOME/miniconda/epics;
        rm -f $EPICS_BASE/lib/$EPICS_HOST_ARCH/*.so*;
        rm -f $EPICS_BASE/lib/$EPICS_HOST_ARCH/*.dylib*;
        if [[ $TRAVIS_OS_NAME == "linux" && $CONDA_PY == "2.7" ]]; then
            python setup.py sdist upload -r mypypi;
        fi;
        if [[ $TRAVIS_OS_NAME == "linux" ]]; then
            python setup.py bdist_egg upload -r mypypi;
        fi;
        if [[ $TRAVIS_OS_NAME == "osx" ]]; then
            python setup.py bdist_wheel upload -r mypypi;
        fi;
      fi
