os:
    - linux
    - osx

matrix:
    - CONDA_PY=2
    - CONDA_PY=3

install:
  # Set the anaconda environment
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      if [[ "$CONDA_PY" == "2" ]]; then
        curl https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -o miniconda.sh;
      else
        curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh;
      fi
    else
      if [[ "$CONDA_PY" == "2" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set auto_update_conda False
  - conda update -q --all
  - conda install conda-build numpy anaconda-client
  # build
  - conda config --add channels paulscherrerinstitute
  - conda build conda-recipe
  - conda install pcaspy --use-local

script:
  - cd test; python gddTest.py

deploy:
  script: anaconda -t $CONDA_TOKEN upload $HOME/miniconda/conda-bld/${TRAVIS_OS_NAME}-64/*.tar.bz2
