
package:
  name: pcaspy
  version: 0.7.1

source:
  # fn: pcaspy-0.5.1.tar.gz
  # url: https://pypi.python.org/packages/source/p/pcaspy/pcaspy-0.5.1.tar.gz
  # md5: ba8c56ef136540cbaa463d35385b4c42
  path: ..
  patches:
    - readline.patch # [linux]

requirements:
  build:
    - python
    - setuptools
    - wheel
    - epics-base
    - swig

  run:
    - python
    - epics-base # [not win]

test:
  requires:
    - numpy

  source_files:
    - test/gddTest.py

  commands:
    - python test/gddTest.py

about:
  home: https://github.com/paulscherrerinstitute/pcaspy
  license: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
